### PR TITLE
Ticket 5257: removed mbbi/mbbo field definitions

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by Alexandru-Dascalu — CHANGES_REQUESTED** [review]
The changes make the tests pass, however we still do not know exactly what has changed and where in our dependencies it has changed, so we should ask in tech talk if anyone knows about this. We should then document what exactly has changed in EPICS, if this is a bug, a fix for a bug, or just a change in functionality. The documentation should also explain the weird behaviour I have described on the ticket. The outcome of the investigation might also lead to changes to the fix.

I have added some information I have gathered in the ticket as a comment. Some of the behaviour documented on the ticket is weird, so we should know

**Comment by Alexandru-Dascalu** [comment]
It might be possible that the tests fail because our testing framework no longer works correctly with EPICS. See the ticket.

**Comment by ghost** [comment]
1. We ideally do not re-index mbbo/mbbi records without good reason. 
1. This change is removing code that is not required, and in instances you have used different indexes in the driver which can cause confusion as it is not consistent.
1. In cases where you have re-indexed from 0 -> 1 what happens when the record initialises (by default 0)?
1. The remove of this code does not regress the behaviour of the previous version. The change can be tested on both versions and all tests pass. 

I would argue this is just removing code that is not required.

**Review by Alexandru-Dascalu — APPROVED** [review]
The documentation will be done in another ticket that will be for all mbbos in all IOCs, so ther is nothing else to do.

**Pull request merged**
